### ISSUE TITLE
Feature Request: 3-speed Fan Control IR device as single Home app fan device 

### ISSUE THREAD

**Issue by Kositch** [OpenWonderLabs/homebridge-switchbot#1033]
### Problem

Switchbot IR fan device with 3 speed buttons and 1 Off button shows up in Home app as On/Off fan without any possibility to switch different speeds. 

### Solution

Fan device with speed control in Home app which turns on Speed 1 switchbot IR control button when for example speed set in Home app between 1-30%, turns on Speed 2 button when set 30-60% etc...

### Alternatives

Alternatively I have created 3 fan devices in switchbot app which each turns On different speed and then there are 3 single On/Off fans in Home app each for turning different fan speed. Works but one single fan device would be better.

### Additional context

Using switchbot plugin version 3.4.0 because of issue #1021 - so if it is already implemented, please let me know. When I check the box Enable speed control nothing happens, device in Home app is still On/Off fan.

**Comment by donavanbecker** [comment]
Closing all issues now that v4.0.0 is out. If you are still having an issue after trying v4.0.0, please open a new issue. Keep in mind v4.0.0 has some breaking changes with the config. You will need to re set your config up, however there are some nice added bonuses since you can set settings at a deviceType level or individual level.
