### ISSUE TITLE
Support Request: What is EVE history

### ISSUE THREAD

**Issue by Hk1020** [OpenWonderLabs/homebridge-switchbot#1054]
### Describe Your Problem

There is a setting `EVE history` in the Outdoor Thermometer device settings. What is it supposed to do? I’d expect some historical data in the EVE app but there is nothing when I turn it on. I’d like something like the Switchbot app on the iPad. 

### Device & Model

Outdoor Thermometer 

### Node.js Version

v20.16.0

### NPM Version

10.2.3

### Homebridge Version

v1.8.4

### Homebridge SwitchBot Plugin Version

v3.7.0

### Homebridge Config UI X Plugin Version

v4.58.0

### Operating System

Raspian

**Comment by donavanbecker** [comment]
Do you have logs to show that it isn't sending anything from the plugin?

**Comment by donavanbecker** [comment]
Closing all issues now that v4.0.0 is out. If you are still having an issue after trying v4.0.0, please open a new issue. Keep in mind v4.0.0 has some breaking changes with the config. You will need to re set your config up, however there are some nice added bonuses since you can set settings at a deviceType level or individual level.

**Comment by Hk1020** [comment]
> Do you have logs to show that it isn't sending anything from the plugin?

I don’t know. I just don’t know what this option is supposed to do. v4.0.0 doesn’t change anything as far as I can tell.
