### ISSUE TITLE
Remove Light Sensor Without Adding Curtain from Scratch

### ISSUE THREAD

**Issue by FranciRoosters** [OpenWonderLabs/homebridge-switchbot#212]
### Describe Your Problem

I have added my SwitchBot Curtains through OpenAPI and as such the curtains don't show under Optional SwitchBot Device Settings, but under the Settings tab. I'd like to remove the light sensor as I don't need them, but I don't wanna go through the set-up process again. If possible, how can I do this? Thanks!

### Device & Model

SwitchBot Curtain, latest model

### Node.js Version

16.13.2

### NPM Version

8.1.2

### Homebridge Version

1.3.9

### Homebridge SwitchBot Plugin Version

1.9.0

### Homebridge Config UI X Plugin Version

4.41.5

### Operating System

Raspbian

**Comment by donavanbecker** [comment]
@FranciRoosters What do you mean setup process?

If you add a new device to your SwitchBot account, you can always grabs the device ID, from the device info and then populate it in the SwitchBot settings before restarting homebridge to look for the device.

Other then that if a device is added to homebridge, and then you change the settings, I remove the service and not the whole device, so you should have no issue letting homebridge find the device, then adding the setting, and then restarting again.

Also might not be a bad idea to put each of your plugins into child bridges so that you can restart that specific child bridge instead of the whole homebridge process.

**Comment by FranciRoosters** [comment]
Thank you for your clarifications. That helped me sort it out.

**Comment by donavanbecker** [comment]
Awesome!
