### ISSUE TITLE
Bug: "Door" accessory never enters "Open" state in HomeKit

### ISSUE THREAD

**Issue by xhi-nico** [OpenWonderLabs/homebridge-switchbot#430]
### Describe The Bug

When Bot is used to open a door, HomeKit only sees "Openning" state, never actually "Open"

### To Reproduce

Using a SwitchBot, show as Door accessory 

### Expected behavior

The "Door" accessory in HomeKit should receive a "Open" state at least for a second; otherwise HomeKit automations won't work because it never recognizes the door actually opened. It only see's that it attempted to open via "Openning" state.

### Relevant log output

```shell
[23/07/2022, 12:46:12] [SwitchBot] Bot: Door Buzzer Sending request to SwitchBot API. command: press, parameter: default, commandType: command
[23/07/2022, 12:46:12] [SwitchBot] Bot: Door Buzzer Sending request to SwitchBot API. command: press, parameter: default, commandType: command
```

### Config for homebridge-switchbot

```shell
{
                        "deviceId": "--",
                        "configDeviceName": "Door Buzzer",
                        "hide_device": false,
                        "offline": true,
                        "configDeviceType": "Bot",
                        "ble": false,
                        "bot": {
                            "mode": "press",
                            "deviceType": "switch",
                            "allowPush": true,
                            "doublePress": 2
                        }
```

### Device & Model

SwitchBot

### Node.js Version

v14.17.6

### NPM Version

v7.22.0

### Homebridge Version

v1.3.5

### Homebridge Switchbot Plugin Version

LATEST

### Operating System

Raspbian

**Comment by iSteve-O** [comment]
I used to have my coffee maker bot set to "press" mode in Homebridge config and it was annoying because as soon as it would turn on it would go back off ("stateless"). 

I changed the mode from press to "switch," and the HomeKit tile went from stateless to normal staying on until turned off, and now matches my coffee maker. On the rare occasion something funky happens it may get out of sync at you'll have to tap the button manually or in the switchbot app to sync the bot back to HomeKit, but maybe this will help you. This seems like a logical explanation as to why the door never showed as open (at least not open long enough to notice). I hope that works.
