### ISSUE TITLE
Feature Request: Delay Off

### ISSUE THREAD

**Issue by dampney** [OpenWonderLabs/homebridge-switchbot#445]
### Solution

Is there a way to DelayOff a Bot so the ‘on’ state turns ‘off’ after a select period of time?

### Problem

I have a Bot on my Coffee Machine, and when it turns on by my SwitchBot, the Machine stays ‘on’ for 9 minutes, and I’d like to keep it on so when someone activates it in Homekit or via Siri, the Coffee Machine stays ‘on’ instead of accidentally getting turned off.

**Comment by iSteve-O** [comment]
try changing your bot's "mode" from "press" to "switch" in the homebridge config. The default behavior is a "momentary" stateless switch that turns itself off after a few minutes without working the bot, but when I changed this mode in hombridge I was able to have it stay in sync with my coffee maker and then I could also make an auto-off automation (and say off to Siri and have it work), now that the bot acts as a "stateful" switch. I hope this helps you, as it's not very clear in the documentation. If it ever gets out of sync because someone hit the physical button or whatever just work it in the switchbot app until it's back in sync. Good luck!

This is how mine is configured to be stateful...
`.         {

            "name": "SwitchBot",

            "credentials": {

                "openToken": "my-token",

                "notice": "Keep your token a secret!"

            },

            "options": {

                "devices": [

                    {

                        "deviceId": "DA07E0740D6C",

                        "configDeviceType": "Bot",

                        "bot": {

                            "mode": "switch",

                            "deviceType": "switch"

                        }

                    }

                ]

            },

            "platform": "SwitchBot",

            "_bridge": {

                "username": "00:00:00:00:00:00",

                "port": 38561

            }`

Good luck!
