### ISSUE TITLE
Feature Request: Switchbot Lock operate the Deadlock via Homekit

### ISSUE THREAD

**Issue by Lling** [OpenWonderLabs/homebridge-switchbot#622]
### Problem

Via Homekit, you cant use the deadlock without locking/unlocking the lock.

### Solution

Separate Switch for operating the deadlock if the lock ist unlocked

**Comment by donavanbecker** [comment]
@Lling Not really sure what you mean? I have tested the lock and it works fine with deadbolt locks.

**Comment by Lling** [comment]
Ok i will try it to explane.
In homekit you have the switch to lock and unlock the switchbot lock.
If the door is locked and you turn switch, the door gets unlocked and the deadbolt open the door.
But when the door is unlocked and closed you have to lock it first and unlock it again to use the deadbold.
So it would be nice to have a separte button or whatever to use the deadlock only.
Its like in the switchbot app.
If there the switchbot lock have the status unlocked. You get two options. First option is lock and the second option is use the deadbold to open the door.

**Comment by donavanbecker** [comment]
@Lling Is this a dual lock setup?

**Comment by Lling** [comment]
No its only one lock.
In the switchbot app you have these option.
If the lock is unlock an the door is close.
If you you click in the switchbot app on the icon you get two options.
First option: lock the door.
Second option: operate the deadbold. And these option you dont have in the homebridge/homekit app.

**Comment by Bat-Maniac** [comment]
This function is generally not supported by HomeKit, not even with HK certified smart locks.
The tedee smart lock for example, when the door is unlocked, you can quickly pull the switch up and down in the Home app, which triggers the deadlock.
I can't say if this also works with the SwitchBot Lock because I don't have it at the moment.
But I will test it in the near future.

Maybe you can create a dummy switch in homebridge yourself, and then create an automation in the controller for HomeKit app (if deadlock is available through the plugin in the controller app).
