### ISSUE TITLE
Feature Request: Ability to choose type of device

### ISSUE THREAD

**Issue by bastiengrignon** [OpenWonderLabs/homebridge-switchbot#67]
### Problem

Wrong icon in HomeKit

### Solution

It could be nice to be able to choose the type of sensor for Switchbot device. I'm currently using a simple Switchbot Bot for my electric store and that could be nice to show it as a store in HomeKit, but it is currently showing as an outlet, and it can only be showed as : 
- an outlet  
- a fan  
- a light

### Alternatives
Adding other type of sensor of SwitchBot Bot as it can be used for many things: 
- contact sensor
- door
- garage door
- blinds
- window
- ...

### Additional context

I've seen that you've also done SwitchBot x No-IP, and this No-IP accessory in Homekit can be displayed as one of the type mentioned above

**Comment by donavanbecker** [comment]
> contact sensor
> door
> garage door
> blinds
> window

I could potentially do blinds but there are 3 required Characteristics and I can only send off and on with a Switch Bot

https://developers.homebridge.io/#/service/WindowCovering

Same thing with the garage door:

https://developers.homebridge.io/#/service/GarageDoorOpener

As for the other 3 you have listed, it wouldn't be practical to show them as those types since you can't interact with those HomeKit times.

The Current types supported are the only practical once as of now, if other practical ones are suggested then I can look at adding those types.
