### ISSUE TITLE
Feature Request: Add a Latch Function for the Lock

### ISSUE THREAD

**Issue by quebulm** [OpenWonderLabs/homebridge-switchbot#833]
### Problem

Users may find themselves in situations where they want to re-unlock a smart lock without having to lock it first. The current implementation does not support this functionality, requiring the user to lock and then unlock the device to achieve the same result.

### Solution

Introduce a "Latch" function that allows the lock to be re-unlocked even if it is already in an unlocked state.

### Alternatives

An alternative could be to introduce a "toggle" function that flips the lock state regardless of its current state (locked/unlocked). However, this might not be as intuitive or specific as a dedicated "Latch" function.

### Additional context

One common scenario that highlights the need for this feature is when a user simply closes the door behind them without locking it and later wants to re-enter. In the current implementation, the user would have to manually lock the door in the HomeKit app and then unlock it again to activate the latch function.

**Comment by gershhub** [comment]
Came here to file the same issue-- night latch doors make the Homebridge plugin rather cumbersome in practice. The API only exposes `lock` and `unlock` commands, and not `unlatch` as offered in the native app. This would have to be a stateless trigger button that issues an unlock command regardless of the current state. The dummy button workaround seems common in other popular Homebridge plugins, and could be an opt-in option for anyone with a night latch configuration. Hopefully Apple will work this out for everyone eventually.

I've observed that manually setting up a dummy switch using the Homebridge Dummy plugin and mapping the action to `unlock` as an automation does not work. Apple seems to block issuing an `unlock` if the device state is already unlocked. But perhaps this approach could work via direct API call rather than passing through the Homekit lock.

**Comment by quebulm** [comment]
Just a quick update on this - I've gone ahead and forked the repo to add a "Latch" function. It's a simple switch that sends an unlock command through the API, no matter the current lock state. I aimed for the switch to snap back to "off" after activation, to act like a push button. It's mostly there, but the auto-off feature isn't fully reliable yet. I'm new to contributing to projects like this, so any feedback would be helpful.

https://github.com/quebulm/homebridge-switchbot/tree/feature/add-latch-to-lock-%23833

**Comment by donavanbecker** [comment]
@quebulm, when ever you feel ready. let me know here, I will open a new beta branch and we can push it out to beta for people to try.

**Comment by quebulm** [comment]
Hey @donavanbecker. I think it works now - as far as I've tested. I added it as an optional feature which you can activate in the "SwitchBot Device Settings" for the Lock.

**Comment by donavanbecker** [comment]
Perfect, @quebulm I have branch `beta-2.11.0` available. If you can open a PR directing to that branch, we can push out a beta release.

**Comment by donavanbecker** [comment]
The new beta should be published soon.

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=2.11.0-beta.0/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

**Comment by donavanbecker** [comment]
v2.11.0 has been released
